[FIX] mail, account: prevent error when sending invoices in batch
Currently, an error occurs when sending invoices in bulk.

Steps to Reproduce:
 - Install the account module.
 - Go to Email Templates and open Invoice: Sending.
 - Uncheck the Default Recipients, and enter demo@gmail.com in the Cc field.
 - Go to Invoices.
 - Select multiple invoices and click Send.

KeyError: <NewId origin=33>

This error occurs when sending invoices in bulk. As mentioned in commit
https://github.com/odoo/odoo/commit/058d324855a6e2fe3df51386aa153d46419766bf,
the issue was introduced in commit
https://github.com/odoo/odoo/commit/39d1907d77ca9c88431e7e9dc9e8c938c, where
the _compute_alerts method attemptsto set an alert in the wizard. However,
since this is a computed field, the wizard record has a NewId. When trying to
access record.id, it returns a NewId [1],and later, when this NewId is used
as a res_id [2], it raises a KeyError.

[1] https://github.com/odoo/odoo/blob/c70bca77d0447b005b3898e1861facc2828475fc/addons/mail/models/mail_thread.py#L2037

[2] https://github.com/odoo/odoo/blob/c70bca77d0447b005b3898e1861facc2828475fc/addons/mail/models/mail_thread.py#L2084

This commit will fix the above issue by using _origin.id, ensuring that it
always returns the ID of a valid record.

sentry-6562659542