[FIX] hr: prevent error when creating users from employees with existing email
This error is triggered when creating a users from employee records.

Steps to Reproduce:
 - Install the hr module.
 - create a user.
 - Create an employee using the same email as the user.
 - In the newly created employee record, click the Create User action.

ValueError: `UniqueViolation('duplicate key value violates u ...`

This error occurs when attempting to create users from employee records, but
user with the same email already exists in the system.

This commit ensures that users are created for employees only if no existing
user is using the same email address. If a user with the employee's email
already exists, a warning notification is displayed instead of error.

This commit also uses `self._env._()` instead of `_()` to ensure lang is
available while using it in a test case.

sentry-6600672947