[FIX] web: prevent crash on website editor
__Current behavior before commit:__
jQuery has been removed from `web.assets_backend` in [`b8fc93e`][1],
now it's dynamically added with the `ensureJQuery` method.
A lot of customers put `web/static/lib/jquery/jquery.js` in
`web.assets_backend` (using custom modules) but not
`web/static/src/legacy/js/libs/jquery.js`. Therefore `ensureJQuery`
doesn't fetch `web._assets_jquery` and therefore
`web/static/src/legacy/js/libs/jquery.js` is never included.

__Description of the fix:__
If jQuery is present, check if the method `getScrollingElement` is defined in
jQuery. If not fetch it.

__Steps to reproduce the issue in local:__
1. Add back "web/static/lib/jquery/jquery.js" in the `web.assets_backend`
entry of `addons/web/\_\_manifest\_\_.py` to simulate that a customer
added it in a custom module.
2. Open the database and Refresh Assets in the debug menu
3. Try to open the editor
Crash: "TypeError: $(...).getScrollingElement is not a function"

opw-4499576

[1]: https://github.com/odoo/odoo/commit/b8fc93ea97b8