[FIX] base: prevent error when update path is not defined in automation action
When executing an automation rule with an "Update Record" action, if no
update path is configured, an error occurs.

Steps to reproduce:
1. Install the CRM and Automation Rules modules.
2. Create a new automation rule:
 - Model = Lead, Trigger = After Creation
3. Add an action. Type = Update Record (do not configure the update path)
 (Tip: select another action type and switch back to reset the path.)
4. Create a new lead.
5. Run the scheduled action: Automation Rules: check and execute.

Error:
```
AttributeError: 'bool' object has no attribute 'split'
....
ValueError: AttributeError("'bool' object has no attribute 'split'") while
evaluating 'model._cron_process_time_based_actions()'
```

Cause:
In `_traverse_path`, the `update_path` is expected to be a string for `.split()`,
but if not configured, it is `False`, leading to the traceback. - [1]

[1] - https://github.com/odoo/odoo/blob/5842c9f4821772fe44cfe7244162edec1ffff88e/odoo/addons/base/models/ir_actions.py#L701

Fix:
This commit ensures that no action is performed if the update path is not
defined, avoiding the traceback.

sentry-6722927119